### ISSUE TITLE
Mind adding "counter_container_class" as an configuration option?

### ISSUE THREAD

**Issue by ternary-Operator** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#10]
... it would make styling a lot easier, espacially when you have more than one counter.

      
      var defaults = {
        ...
        ...
        // Custom class for counter container
        counter_container_class: ''
      };
------------------------------------------------
      var methods = {
        init: function ($obj) {
          ...
          ...
          // Insert counter after or before text area/box
          $countObj = $("<span id=" + counterID + "/>");
          var counterDiv = $('<div/>')
            .attr('id', objID + '_counter')
            .addClass((options.counter_container_class && options.counter_container_class != '') ? options.counter_container_class : '')
            .append($countObj)
            .append(" " + methods.setMsg());

**Comment by qwertypants** [comment]
That sounds like a good idea. Care to create a PR for this so I can merge it (after testing)?
