### ISSUE TITLE
Container Class is Incorrect

### ISSUE THREAD

**Issue by chrisbo** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#13]
You state containerClass in your example, but it is container_class in your script

**Comment by qwertypants** [comment]
@chrisbo  This is actually correct. However, I just realized that this comes across confusing. 

I updated the example for clarity. https://github.com/qwertypants/jQuery-Word-and-Character-Counter-Plugin/commit/743df5bb27ac83e6079e5af42c1e1100e97fb899

http://qwertypants.github.io/jQuery-Word-and-Character-Counter-Plugin/#containerClass

Thanks!
