### ISSUE TITLE
Add support for 'contenteditable' elements

### ISSUE THREAD

**Issue by Globulopolis** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#17]
Hi!

@qwertypants can you add support for this tags?

```
$('.editor').counter({ // $('#editor') doesn't work too
	append: false,
	target: '#word-counter'
});
...
<div class="editor" contenteditable="true"></div>
<textarea id="editor"></textarea>
<div id="word-counter"></div>
```

#word-counter still display initial value for counter even if it's reaches the limit.

And thank you for great plugin!

**Comment by qwertypants** [comment]
Thanks for the suggestion. I just published and update to include this feature!

Check out the demo (at the bottom): http://qwertypants.github.io/jQuery-Word-and-Character-Counter-Plugin/ 

Enjoy!

**Comment by Mustafaoeztuerk** [comment]
@qwertypants Not supporting contenteditable. It just countdown character. I have try to use with goal: 100, but it just count down the character. I can write some other word, it should work when character 100 then user can not write any other character.
