### ISSUE TITLE
Chrome - wrong New Lines counting

### ISSUE THREAD

**Issue by LukSkywookie** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#21]
Hi!:)
I did something like that 
`$("textarea").counter({
            count: 'down',
            goal: 300,
            target: '.counter span',
            text: false
        });`
Unfortunatly it counts wrong in chrome. Every "enter" sign cousing problem. When i reach max length counter says that few chars left, but I can't write no more characters.

I'm using only min.js file.
Can you help me?:)

**Comment by qwertypants** [comment]
Hey @LukSkywookie. I wasn't able to reproduce this. 

I recently updated this plugin to support jQuery 3, hopefully that might have made a difference. 
You can experiment here: http://codepen.io/qwertypants/pen/JbGqMY

Thanks!
