### ISSUE TITLE
jQuery.fn.bind() is deprecated for Jquery 3

### ISSUE THREAD

**Issue by tlandn** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#22]
Hi, I am upgrading my app using Jquery 3, I used Jquery migrate and see this warning JQMIGRATE: jQuery.fn.bind() is deprecated

From http://api.jquery.com/bind/, .bind() is deprecated in Jquery 3

Thanks

**Comment by qwertypants** [comment]
@tlandn Thanks! I just updated it. Enjoy!
