### ISSUE TITLE
containerClass not in latest build

### ISSUE THREAD

**Issue by Joyrex** [qwertypants/jQuery-Word-and-Character-Counter-Plugin#24]
Spent hours trying to figure out why `containerClass` from the docs wasn't working in the version I downloaded (2.4) - finally wired up my page to use the script called by the demo and it works.

Searched the  minified text for `containerClass` and it's not even in there.

**Comment by Joyrex** [comment]
Come to mention it, why does the minified version in the latest download (which is 2.3.5) say `v2.4` in the script?

**Comment by qwertypants** [comment]
Oh noes! Sorry you had to go through that  😢. 

The latest version is 2.5. You can [download it directly](https://raw.githubusercontent.com/qwertypants/jQuery-Word-and-Character-Counter-Plugin/master/jquery.word-and-character-counter.min.js) or use `npm install jquery-word-and-character-counter-plugin`
